### ISSUE TITLE
Does this work relate to a paper? 

### ISSUE THREAD

**Issue by anl13** [G-Apple1/SMALify-Pig3D#1]
Hello, I find the fitting results are impressive. Is there any manuscript or paper linked to this project?

**Comment by G-Apple1** [comment]
> Hello, I find the fitting results are impressive. Is there any manuscript or paper linked to this project?

The paper is writting now, so if you want to know more, we can add a contact.

**Comment by anl13** [comment]
> > Hello, I find the fitting results are impressive. Is there any manuscript or paper linked to this project?
> 
> The paper is writting now, so if you want to know more, we can add a contact.

Sure, my email is al17@mails.tsinghua.edu.cn , could you send me your contact information personally ? Then I could link to you.
